---
title: "ggplot2 Centralization Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(tidyverse)
library(data.table)
dataset <- hlm_data <- fread("~/nba_long_nets_ready_for_hlm_2.csv")
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

checkboxInput('Teams', 'Teams', value = c("ATL"))
checkboxInput('Seasons', 'Seasons', value = c("2014"))

selectInput('x', 'X Variable', names(dataset))
selectInput('y', 'Y Variable', names(dataset), names(dataset)[[2]])
selectInput('color', 'Color', c('None', names(dataset)))

selectInput('facet_row', 'Facet Row',
            c(None='.', names(dataset[sapply(dataset, is.factor)])))
selectInput('facet_col', 'Facet Column',
            c(None='.', names(dataset[sapply(dataset, is.factor)])))
```

Outputs
-----------------------------------------------------------------------

### Graphic

```{r}
dataset <- reactive({
  dataset[sample(nrow(dataset), input$sampleSize),]
})

renderPlot({
  
  hlm_data %>% group_by(Coach) %>% 
  mutate(mean_centralization = mean(tot_deg_cent)) %>%
  mutate(Coach_Category = case_when(tot_deg_cent >= 0.2959078 ~ "High",
                        tot_deg_cent <= 0.2959078  & tot_deg_cent >= 0.2632196
                        ~"Mid",
                               tot_deg_cent <= 0.2632196 ~ "Low")) 
  p <- ggplot(dataset(), aes_string(x=input$x, y=input$y)) + geom_point()
  
  if (input$color != 'None')
    p <- p + aes_string(color=input$color)
  
  facets <- paste(input$facet_row, '~', input$facet_col)
  if (facets != '. ~ .')
    p <- p + facet_grid(facets)
  
  if (input$jitter)
    p <- p + geom_jitter()
  if (input$smooth)
    p <- p + geom_smooth()
  
  print(p)
})
```