---
title: "R Notebook"
output: html_notebook
---

 

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(tibble)
library(lubridate)
```

#added files into enviornment through the import data set in R studio. This is justhe visulaization of that.
```{r}
nba_odds_2013_14 <- read_excel("NBA odds 2013-2018/nba odds 2013-14.xlsx")
nba_odds_2014_15 <- read_excel("NBA odds 2013-2018/nba odds 2014-15.xlsx")
nba_odds_2015_16 <- read_excel("NBA odds 2013-2018/nba odds 2015-16.xlsx")
nba_odds_2016_17 <- read_excel("NBA odds 2013-2018/nba odds 2016-17.xlsx")
nba_odds_2017_18 <- read_excel("NBA odds 2013-2018/nba odds 2017-18.xlsx")
```

#Adds and fills the year column, adds the opponent column, and adds the win/loss columns
```{r}
nba_odds_2013_14$Year <- "2013-14"
nba_odds_2014_15$Year <- "2014-15"
nba_odds_2015_16$Year <- "2015-16"
nba_odds_2016_17$Year <- "2016-17"
nba_odds_2017_18$Year <- "2017-18"

nba_odds_2013_14 <- nba_odds_2013_14 %>% add_column(Opponent = NA)
nba_odds_13_18 <- nba_odds_13_18 %>% add_column(Opponent = NA)
nba_odds_13_18 <- nba_odds_13_18 %>% add_column(WinLoss = NA)

as.Date(as.character(nba_odds_2013_14[[1,1]]), format = "%m%d")
nba_odds_2013_14[[1,1]]
```

#Combines all the individual tables into one table
```{r}
nba_odds_13_18 <- rbind(nba_odds_2013_14, nba_odds_2014_15, nba_odds_2015_16, nba_odds_2016_17, nba_odds_2017_18)
```

#filling in the opponent column 
```{r}

for (k in seq(2, nrow(nba_odds_13_18[,1]), 2)) {
  nba_odds_13_18[k,15] <- nba_odds_13_18[[k-1,4]]
}

for (i in seq(1, nrow(nba_odds_13_18[,1]), 2)) {
  nba_odds_13_18[i,15] <- nba_odds_13_18[[i+1,4]]
}
```

#Filling in the Win and loss column
```{r}

for (l in seq(1, nrow(nba_odds_13_18[,1]), 2)) {
  if(nba_odds_13_18[[l,9]] > nba_odds_13_18[[l+1,9]]){
    nba_odds_13_18[l,16] <- 'W'
    nba_odds_13_18[l+1,16] <- 'L'
  }
  else if(nba_odds_13_18[[l,9]] < nba_odds_13_18[[l+1,9]]){
    nba_odds_13_18[l,16] <- 'L'
    nba_odds_13_18[l+1, 16] <- 'W'
  }
  else{
    nba_odds_13_18[l,16] <- 'T'
    nba_odds_13_18[l+1, 16] <- 'T'
  }
    
}

```


#Wins and losses as favorite and underdog
```{r}

nba_odds_13_18 %>% group_by(Team) %>% 
  group_by(ML <= 100, WinLoss )%>% count()
  
```





